apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: ${namespace}
  labels:
    app: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ratings-${version}
  namespace: ${namespace}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings
        version: ${version}
    spec:
      containers:
      - name: ratings
        image: bevyx/demo-bookinfo-ratings:${version}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080